// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "KOKYO",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "KOKYO",
            targets: ["AppModule"],
            bundleIdentifier: "com.hamamatsu.I-SPY",
            teamIdentifier: "UX4Y5TQ52G",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Unknown Usage Description")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/YOLOv3TinyFP16.mlmodelc"),
                .copy("Resources/DefaultBackground.jpg")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)